### PR TITLE
Remove opt-out functionality

### PR DESCRIPTION
**Pull request by jb3**
This PR removes the opt out data from the database and the related opt out commands from the bot.

Data gathered from Metricity is used in various places around the community now, including but not limited to:
- Voice verification
- Nomination information
- Channel usage measurements

The opt-out functionality is somewhat misleading since the only data it opts out from is from collection of message counters, all data collected prior is retained as well as user information. There is no compliance reason to have opt out functionality.

Data from Metricity can still be removed however it will go through the regular erasure process defined by the data processor with more information in the privacy policy, however this does mean that metricity data is considered essential for the operation of the community and therefore will not be removed while users are members.

~~:warning: There are privacy policy amendments that should be made before this PR is merged.~~

### CODE REVIEW

**Comment by jb3** [comment]
Note to self: this should be changelogged when merged, with some of the above explanation included.

**Review by bsoyka — APPROVED** [review]
I agree with DawnOfMidnight - code looks good and after a short ~~interrogation~~ discussion with Joe, this definitely makes things clearer.

Much easier to say you can't opt out at all than to allow opting out of one small aspect of Metricity.

**Review by Akarys42 — APPROVED** [review]
The changes looks good, I'm going to trust you for the privacy policy part :+1:

**Comment by jb3** [comment]
Privacy policy amendments and announcement have been made. This PR can be merged any time after 12 UTC on Sunday April 18th.

**Comment by dawnofmidnight** [comment]
Does this update the help command? I might just be blind, but I don't see where it does. Unless that's a plan for a separate pr.

**Comment by ToxicKidz** [comment]
> Does this update the help command? I might just be blind, but I don't see where it does. Unless that's a plan for a separate pr.

When you remove a command, it automatically updates the help command.

**Comment by onerandomusername** [comment]
> 
> 
> > Does this update the help command? I might just be blind, but I don't see where it does. Unless that's a plan for a separate pr.
> 
> When you remove a command, it automatically updates the help command.

But since there will no longer be any commands, it would make sense to either remove or edit the `m!help` command to reflect what the bot is, perhaps be an about command instead.

**Comment by jb3** [comment]
I think it's fairly fine, you'd have to know `m!help` even existed to try it. If we want then a subsequent PR can implement that.

**Comment by dawnofmidnight** [comment]
> > Does this update the help command? I might just be blind, but I don't see where it does. Unless that's a plan for a separate pr.
> 
> When you remove a command, it automatically updates the help command.

Completely forgot about that, thanks!

**Comment by jb3** [comment]
image

**Comment by onerandomusername** [comment]
> image

I feel teased.

**Pull request merged**
